# Generated by Django 6.1 on 2026-08-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_brand_product_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], default='women', max_length=20),
        ),
    ]
